name: Actions Matcher Test
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "##[add-matcher]$(pwd)/eslint-compact.json"
      - run: >
          echo "$(pwd)/index.js: line 11, col 1, Warning - 1111. (no-var)"
      - run: >
          echo "index.js: line 11, col 1, Warning - 2222 (no-var)"
